# One Hot Encoding

In [1]:
import numpy as np
import pandas as pd

In [7]:
df=pd.read_csv('Data_set/data.csv')
df

Unnamed: 0     town  price  area
0           0      ktm   2000   200
1           1      brt   5000   400
2           2  pokhara   7000   600
3           3      ktm  10000   800
4           4      brt   5000   800
5           5  pokhara   6000   300
6           6      ktm   3000   400
7           7      brt   5000   500
8           8  pokhara   4000   250

In [12]:
dummies=pd.get_dummies(df.town)
dummies

brt    ktm  pokhara
0  False   True    False
1   True  False    False
2  False  False     True
3  False   True    False
4   True  False    False
5  False  False     True
6  False   True    False
7   True  False    False
8  False  False     True

In [13]:
merged=pd.concat([df,dummies],axis='columns')
merged

Unnamed: 0     town  price  area    brt    ktm  pokhara
0           0      ktm   2000   200  False   True    False
1           1      brt   5000   400   True  False    False
2           2  pokhara   7000   600  False  False     True
3           3      ktm  10000   800  False   True    False
4           4      brt   5000   800   True  False    False
5           5  pokhara   6000   300  False  False     True
6           6      ktm   3000   400  False   True    False
7           7      brt   5000   500   True  False    False
8           8  pokhara   4000   250  False  False     True

In [17]:
final_df=merged.drop(['town','pokhara'],axis='columns')
final_df

Unnamed: 0  price  area    brt    ktm
0           0   2000   200  False   True
1           1   5000   400   True  False
2           2   7000   600  False  False
3           3  10000   800  False   True
4           4   5000   800   True  False
5           5   6000   300  False  False
6           6   3000   400  False   True
7           7   5000   500   True  False
8           8   4000   250  False  False

In [21]:
from sklearn import linear_model
model=linear_model.LinearRegression()

In [33]:
X=final_df.drop(['price'],axis='columns')
X

Unnamed: 0  area    brt    ktm
0           0   200  False   True
1           1   400   True  False
2           2   600  False  False
3           3   800  False   True
4           4   800   True  False
5           5   300  False  False
6           6   400  False   True
7           7   500   True  False
8           8   250  False  False

In [34]:
y=final_df.price
y

0     2000
1     5000
2     7000
3    10000
4     5000
5     6000
6     3000
7     5000
8     4000
Name: price, dtype: int64

In [35]:
model.fit(X,y)

LinearRegression()

In [45]:
model.predict([[0,1,0,0]])

/Users/aaryanshah/Desktop/Machine Learning/env/lib/python3.11/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([2695.98817681])

In [41]:
model.score(X,y)

0.662321397724749

In [47]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [48]:
dfle=df
dfle.town=le.fit_transform(dfle.town)
dfle

Unnamed: 0  town  price  area
0           0     1   2000   200
1           1     0   5000   400
2           2     2   7000   600
3           3     1  10000   800
4           4     0   5000   800
5           5     2   6000   300
6           6     1   3000   400
7           7     0   5000   500
8           8     2   4000   250

In [49]:
Xi=dfle[['town','area']].values
Xi

array([[  1, 200],
       [  0, 400],
       [  2, 600],
       [  1, 800],
       [  0, 800],
       [  2, 300],
       [  1, 400],
       [  0, 500],
       [  2, 250]])

In [52]:
Yi=dfle.price
Yi

0     2000
1     5000
2     7000
3    10000
4     5000
5     6000
6     3000
7     5000
8     4000
Name: price, dtype: int64

In [53]:
from sklearn.preprocessing import OneHotEncoder
Oe=OneHotEncoder(categorcal_features=[0])

In [55]:
X=Oe.fit_transform(Xi).toarray()
X

array([[0., 1., 0., 1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 1., 0., 0., 0., 0., 0.]])

In [56]:
X=X[:,1:]
X

array([[1., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 1., 0., 0., 0., 0., 0.]])

In [57]:
model.fit(X,Yi)

LinearRegression()

In [64]:
model.predict([[1,0,1,0,0,0,0,0,200]])

array([520421.05263158])