In [7]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr[0]*arr[1])


[ 4 10 18]


In [13]:
arr[0,1:3]

array([2, 3])

In [14]:
arr.dtype

dtype('int64')

In [15]:
x=arr.copy()
x

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
y=arr.view()
arr[0][1]=10
arr
y

array([[ 1, 10,  3],
       [ 4,  5,  6]])

In [17]:
y

array([[ 1, 10,  3],
       [ 4,  5,  6]])

In [20]:
print(y.base)
print(arr.base)

[[ 1 10  3]
 [ 4  5  6]]
None


In [23]:
print(arr.shape)

(2, 3)


In [25]:
a=np.array([[1,2],[2,2],[1,2]])
a.shape

(3, 2)

In [29]:
arr.reshape(2, 3)

array([[ 1, 10,  3],
       [ 4,  5,  6]])

In [32]:
a1=np.array([[1,2,3],[2,2,2]])

for x in a1:
    for a in x:
      print(a)

1
2
3
2
2
2


In [35]:
a2=np.array([1,2,1,3,1,4])
print(np.array_split(a2, 3))

[array([1, 2]), array([1, 3]), array([1, 4])]


In [36]:
np.where(a2==1)

(array([0, 2, 4]),)

In [37]:
np.where(a2 % 2==0)

(array([1, 5]),)